version: "3"

services:
  db:
    image: postgres
    container_name: ecomdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=athun123
      - POSTGRES_DB=ecom
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - ecom-network

  app:
    image: athunlal/ecomapp:latest
    ports:
      - "9001:4000"
    depends_on:
      - db
    restart: always
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge
